# Generated by Django 4.0.5 on 2022-06-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followertable',
            name='follow_status',
            field=models.CharField(choices=[('a', 'Accept'), ('p', 'Pending')], default='p', max_length=1),
        ),
        migrations.AddConstraint(
            model_name='followertable',
            constraint=models.UniqueConstraint(fields=('following', 'follower'), name='unique follower'),
        ),
    ]
